version: '3'

services:

  covid:
    
    image: kerxd/breaking-bad:latest

    container_name: docker-breaking-bad

    environment:
      - SERVER_PORT=80

    ports:
      - "88:80"

    networks: 
      - bad-network

    depends_on:
      - mysqldb



  mysqldb:
    image: mysql:8

    container_name: docker-mysql-breaking-bad

    networks:
      - bad-network

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=breaking_bad

      
    volumes:
      - mysql_db:/var/lib/mysql
      
      
volumes:
  mysql_db:

networks:
  bad-network: